Working on notes
telerik/xaml-docs pull request #2491
Opened 2021-12-22 11:20 UTC by DKaramfilov

2021-12-23 08:16 UTC, velikovmartin requested changes

2021-12-23 08:17 UTC, DKaramfilov commented on controls/radspreadsheet/features/notes.md
> +slug: radspreadprocessing-features-notes
fixed

2021-12-23 08:19 UTC, DKaramfilov commented on controls/radspreadsheet/features/notes.md
> +Since R1 2022 the Spreadsheet control supports working with notes. The Notes are used for making notes or annotations about the data. All notes can be found in the __NoteCollection__ of the worksheet
fixed

2021-12-23 08:20 UTC, DKaramfilov commented on controls/radspreadsheet/features/notes.md
> +To edit a note select a cell that contains note and click "Edit Note" from the context menu.
fixed

2021-12-23 08:21 UTC, DKaramfilov commented on controls/radspreadsheet/features/notes.md
> +
added

2021-12-24 09:12 UTC, velikovmartin approved these changes

2021-12-24 09:13 UTC, merged